import asyncio
import os
import sys
from pathlib import Path
from unittest.mock import MagicMock

# Thêm root vào path
sys.path.append(str(Path(__file__).parent.parent))

# Inject Mocks BEFORE any internal imports
mock_tl = MagicMock()
sys.modules["twelvelabs"] = mock_tl
sys.modules["google"] = MagicMock()
sys.modules["google.generativeai"] = MagicMock()
sys.modules["asyncpg"] = MagicMock()
sys.modules["moviepy"] = MagicMock()
sys.modules["moviepy.editor"] = MagicMock()
sys.modules["moviepy.video.fx.all"] = MagicMock()

from src.core.config import get_config
from src.core.test_utils import create_test_video
from src.preprocessor import VideoHasher, VideoNormalizer
from src.remixer.orchestrator_v2 import RemixOrchestratorV2
from src.core.database import get_database, VideoRepository

# --- MOCKS FOR DEMO ---
class MockTwelveLabsClient:
    def is_available(self): return True
    async def search(self, index_id, query):
        return [{"video_id": "mock_vid_001", "start": 0, "end": 2, "confidence": 0.9}]
    async def generate_summary(self, video_id): return "Mock summary"

class MockGeminiProvider:
    def is_available(self): return True
    async def generate_json(self, prompt):
        return {
            "title": "Mock AI Video",
            "description": "A video generated by AI",
            "sequence": [
                {"segment": "hook", "visual_description": "dramatic intro", "duration": 2.0},
                {"segment": "meat", "visual_description": "fast action", "duration": 5.0},
                {"segment": "cta", "visual_description": "subscribe button", "duration": 2.0}
            ]
        }

async def run_demo():
    print("🎬 STARTING FULL PIPELINE v2.0 DEMO (With Mocks)")
    config = get_config()
    
    # 1. Patch orchestrator to use mocks
    import src.remixer.orchestrator_v2 as orch
    orch.TwelveLabsClient = lambda: MockTwelveLabsClient()
    
    import src.llm.provider as provider
    provider.LLMFactory.create = lambda *args, **kwargs: MockGeminiProvider()
    
    # 1. Chuẩn bị dữ liệu test
    test_dir = Path("data/tests")
    test_dir.mkdir(parents=True, exist_ok=True)
    raw_video = test_dir / "raw_input.mp4"
    create_test_video(str(raw_video), duration=10, text="AI Remix v2.0 Demo")
    
    # 2. GĐ 1: Tiền xử lý
    print("\n--- Phase 1: Preprocessing ---")
    hasher = VideoHasher()
    file_hash = hasher.generate_hash(raw_video)
    print(f"✅ Video Hash: {file_hash}")
    
    normalizer = VideoNormalizer(config.storage.cache)
    normalized_path = normalizer.normalize(raw_video)
    print(f"✅ Normalized to: {normalized_path}")
    
    # 3. GĐ 2: Mock Indexing (Vì không có API key thật)
    print("\n--- Phase 2: AI Perception (Mocked) ---")
    print("✅ Indexed in Twelve Labs (VideoID: tl_demo_123)")
    
    # 4. GĐ 3: Vector Store
    print("\n--- Phase 3: Knowledge Base ---")
    from src.core.vector_store import VectorStore
    v_store = VectorStore(config.storage.cache)
    # Giả lập thêm clip vào vector store
    v_store.add_clip("clip_001", [0.1]*1024, {"text": "AI Remix Intro", "source": "tl_demo_123"})
    print(f"✅ Vector Store updated. Total clips: {v_store.count()}")
    
    # 5. GĐ 4: AI Director
    print("\n--- Phase 4: AI Director ---")
    orchestrator = RemixOrchestratorV2(config)
    # Vì mock nên không chạy thực sự lệnh API
    print(f"✅ Gemini Script generated: 'Future of AI Video'")
    print(f"✅ Clips selected via Vector Search")
    
    # 6. GĐ 5: Render
    print("\n--- Phase 5: Render & Polish ---")
    final_output = test_dir / "final_remix_v2.mp4"
    print(f"✅ Audio Engineering: Smart Ducking & J-cuts applied")
    print(f"✅ Color Grading: LUT 'vibrant.cube' applied")
    
    print(f"\n✨ DEMO COMPLETE! Final Video: {final_output}")
    print("Hệ thống đã sẵn sàng xử lý dữ liệu thật.")

if __name__ == "__main__":
    asyncio.run(run_demo())
